### ISSUE TITLE
Error: Cannot find module 'core-js/modules/es6.array.sort'

### ISSUE THREAD

**Issue by THernandez03** [brunocodutra/webapp-webpack-plugin#72] opened 2018-04-12 19:46 UTC
Appear this error when using this plugin with Webpack4. I dont know how to debug plugins very well, so if you need something please tell me or show me how to start with 😄.   

```javascript
× ｢wdm｣: Error: Cannot find module 'core-js/modules/es6.array.sort'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\Projects\my-project\node_modules\favicons\dist\index.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Projects\my-project\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
```

**Comment by brunocodutra** [comment] 2018-04-12 19:54
Could you verify whether adding `"@babel/polyfill": "^7.0.0-beta.42"` as a dependency fixes the issue?

**Comment by THernandez03** [comment] 2018-04-12 20:04
```javascript
Error: Cannot find module 'core-js/modules/es6.array.sort'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (C:\Projects\my-project\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Projects\my-project\node_modules\favicons\dist\index.js:9:1)
    at Module._compile (C:\Projects\my-project\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Projects\my-project\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (C:\Projects\my-project\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Projects\my-project\node_modules\webapp-webpack-plugin\src\loader.js:2:18)
    at Module._compile (C:\Projects\my-project\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Projects\my-project\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (C:\Projects\my-project\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (C:\Projects\my-project\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Projects\my-project\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Projects\my-project\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Projects\my-project\node_modules\loader-runner\lib\LoaderRunner.js:185:6
    at context.callback (C:\Projects\my-project\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Projects\my-project\node_modules\cache-loader\dist\index.js:133:7
    at ReadFileContext.callback (C:\Projects\my-project\node_modules\cache-loader\dist\index.js:200:7)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:434:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! new-project@0.0.1 build: `bash scripts/build.sh "app" "production"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the new-project@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\THernandez\AppData\Roaming\npm-cache\_logs\2018-04-12T20_03_50_958Z-debug.log```

**Comment by brunocodutra** [comment] 2018-04-12 20:12
Is this after adding `@babel/polyfil` as a dependency and running `npm install`?

**Comment by brunocodutra** [comment] 2018-04-12 20:21
I can't seem to be able to reproduce the issue locally on an empty project that depends only on webpack and webapp-webpack-plugin.

Could you paste the relevant parts of your `package.json` and `webpack.config.js`?

**Comment by THernandez03** [comment] 2018-04-13 01:19
I will make a little project until it fails and show you what i'm using. thanks for the response

**Comment by THernandez03** [comment] 2018-04-13 02:17
its solves if i install `core-js` dependency 🤔

**Comment by brunocodutra** [comment] 2018-04-19 06:03
Could you check if [v2.0.3](https://github.com/brunocodutra/webapp-webpack-plugin/releases/tag/v2.0.3) solves the issue?

**Comment by THernandez03** [comment] 2018-04-19 17:33
No. It didn't solve the problem. Also viewing the changes you made to `favicons` repo I tried to install `@babel/core`, `@babel/register` but didn't work either

**Comment by brunocodutra** [comment] 2018-04-19 19:22
Damn it.

Can you share a repo that reproduces the issue?

**Comment by THernandez03** [comment] 2018-04-19 19:41
I share you an invitation to see the project... its in the `upgradeWebpack4` branch. To reproduce the error just install the modules and run `npm run start app`

**Comment by brunocodutra** [comment] 2018-04-19 19:56
I appreciate it, I'll have a look

**Comment by brunocodutra** [comment] 2018-04-19 21:14
After some tinkering I'm convinced the only reasonable solution is indeed to add `core-js` as a dependency. I can't really explain what's going on, but my only guess is that there is some weird interaction going on between babel@6 and babel@7. 

Anyway, since adding core-js as a dependency does solve the problem, I'd say we can close this issue for now and reopen it in case more people report similar issues.

Please let me know what you think.

**Comment by THernandez03** [comment] 2018-04-19 21:26
I think its ok... i thought something similar, but i was not sure at all.

Do you think it's a good idea to put an issue on @babel repo directly ?

**Comment by brunocodutra** [comment] 2018-04-19 21:31
I don't think there's much we can do about it while projects that depend on different major versions of babel coexist, I guess that's the flip side of the paced js/node community, where there is such a thing as packages that evolve *almost* too fast.

**Closed as completed** 2018-04-22 09:25 UTC
Labels: bug

**Comment by dev7ch** [comment] 2018-09-03 13:34
`yarn add babel-preset-env --dev` helped me solving this (using nuxt-edge)

**Comment by Kronhyx** [comment] 2019-02-16 14:50
its solves if i install `core-js` dependency!!! yay!!!, im using nuxt 2.4

**Comment by drewda** [comment] 2019-04-02 22:29
I'm able to get this to work as long as I install `core-js@2.6.5`. The newer 3.0 version does not solve the problem for me.

**Comment by ian** [comment] 2019-04-04 21:06
@drewda's solution works.  Problem seems to be that core-js renamed `es6` directory to `es` gatsby broke as a result.

**Comment by aa-ziyi** [comment] 2019-04-15 03:32
yarn add core-js
如果还不行
删除 node_modules,然后使用 yarn 安装，不要使用 cnpm 安装；

**Comment by giovannimanzoni** [comment] 2019-04-24 07:52
in similar core-js/modules/xxx/yyy error, my solution is to delete node_modules folder and reinstall.

**Comment by Berkmann18** [comment] 2019-12-31 19:34
@ian same goes for Gridsome.
